### ISSUE TITLE
Cannot open include file: 'avro.h': No such file or directory

### ISSUE THREAD

**Issue by bts-webber** [Byhiras/pyavroc#22]
Hi,
     when I use “easy_install” to install pyavro on my windows system,error occurred:

`creating build\temp.win-amd64-2.7\Release\src
    C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -ID:\python2.7\include -ID:\python2.7\PC /Tcsrc/pyavro.c /Fobuild\temp.win-amd64-2.7\Release\src/pyavro.obj
    pyavro.c
    c:\users\administrator\appdata\local\temp\pycharm-packaging\pyavroc\src\convert.h(21) : fatal error C1083: Cannot open include file: 'avro.h': No such file or directory
    error: command 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2`

  How can I solve it ? Thanks.

**Comment by bts-webber** [comment]
Hi,
    I test use centos6.5,no success。

`[webber@localhost site-packages]$ sudo easy_install pyavroc
Searching for pyavroc
Best match: pyavroc 0.7.2
Processing pyavroc-0.7.2-py2.6-linux-x86_64.egg
Adding pyavroc 0.7.2 to easy-install.pth file

Using /usr/lib/python2.6/site-packages/pyavroc-0.7.2-py2.6-linux-x86_64.egg
Processing dependencies for pyavroc
Finished processing dependencies for pyavroc
[webber@localhost site-packages]$ python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyavroc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pyavroc-0.7.2-py2.6-linux-x86_64.egg/pyavroc/__init__.py", line 16, in <module>
  File "/usr/lib/python2.6/site-packages/pyavroc-0.7.2-py2.6-linux-x86_64.egg/pyavroc/_pyavroc.py", line 7, in <module>
  File "/usr/lib/python2.6/site-packages/pyavroc-0.7.2-py2.6-linux-x86_64.egg/pyavroc/_pyavroc.py", line 6, in __bootstrap__
ImportError: liblzma.so.5: cannot open shared object file: No such file or directory
`

**Comment by ruuda** [comment]
I experienced the same problem with Pip. I solved it as follows: clone the repository somewhere and run `./clone_avro_and_build.sh`. I had to install a few requirements in a virtualenv too to make it work. Then:

    mkdir build
    python setup.py bdist_wheel -d build

This will produce a whl file in the build directory, `pyavroc-0.7.2-cp27-cp27mu-linux_x86_64.whl` in my case. Then in a different project and virtualenv, I was able to install this wheel using `pip install /path/too/pyavroc.whl`.

I don’t know how this would be handled with Easy install. Also, building Avro from source on Windows will be a lot harder. You’ll need to perform the equivalent steps of those in `clone_avro_and_build.sh` manually, which requires running CMake to generate a VS solution, then building that solution, retrieving the DLL from there (assuming it compiles at all), ...

@walshb: I think it would help if there would be wheels on Pypi. Would it be possible to upload those?

**Comment by walshb** [comment]
@bts-webber: on CentOS you will have to install the correct compression libraries:

```
sudo yum install zlib xz-libs
easy_install pyavroc
```

Or, as ruuda suggests, you can build from source using `clone_avro_and_build.sh`.

On Windows, the underlying Avro-C code doesn't build. I can probably make it work but I don't have much time right now.

**Comment by walshb** [comment]
@ruuda: I'll take a look at building wheels.
