### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by kaustyap** [Byhiras/pyavroc#34]
Found core on Debian GNU/Linux 10 (buster) with Python 3.7.4-

Program terminated with signal SIGSEGV, Segmentation fault.
#0  insertdict (value=0x0, hash=1972385545398163373, key=0x7f6a317a3c30, mp=0x7f6a317a7eb0) at Objects/dictobject.c:1009
1009    Objects/dictobject.c: No such file or directory.
[Current thread is 1 (Thread 0x7f6a364ce740 (LWP 8))]
(gdb) bt
#0  insertdict (value=0x0, hash=1972385545398163373, key=0x7f6a317a3c30, mp=0x7f6a317a7eb0) at Objects/dictobject.c:1009
#1  PyDict_SetItem (op=op@entry=0x7f6a317a7eb0, key=key@entry=0x7f6a317a3c30, value=value@entry=0x0) at Objects/dictobject.c:1463
#2  0x00007f6a34c8824a in record_to_python (value=0x7ffd5e02a4f0, value=0x7ffd5e02a4f0, info=0x7f6a35e51908) at src/convert.c:211
#3  avro_to_python (info=info@entry=0x7f6a35e51908, value=value@entry=0x7ffd5e02a4f0) at src/convert.c:382
#4  0x00007f6a34c87852 in AvroDeserializer_deserialize (self=self@entry=0x7f6a35e518f0, args=args@entry=0x7f6a35afedd0) at src/deserializer.c:131
#5  0x00007f6a36992985 in _PyMethodDef_RawFastCallKeywords (method=0x7f6a34c8ed60 <AvroDeserializer_methods+32>, self=self@entry=0x7f6a35e518f0,
    args=args@entry=0x7f6a346e5610, nargs=nargs@entry=1, kwnames=kwnames@entry=0x0) at Objects/call.c:698
#6  0x00007f6a3699851d in _PyMethodDescr_FastCallKeywords (descrobj=0x7f6a35a71370, args=args@entry=0x7f6a346e5608, nargs=nargs@entry=2,
    kwnames=kwnames@entry=0x0) at Objects/descrobject.c:288
#7  0x00007f6a36a07385 in call_function (kwnames=0x0, oparg=2, pp_stack=<synthetic pointer>) at Python/ceval.c:4593
#8  _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#9  0x00007f6a36a02631 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0,
    args=args@entry=0x55f49f6fcfb0, argcount=argcount@entry=3, kwnames=0x0, kwargs=0x55f49f6fcfc8, kwcount=<optimized out>, kwstep=1, defs=0x0,
    defcount=0, kwdefs=0x0, closure=0x0, name=0x7f6a35a3f1c0, qualname=0x7f6a35afce10) at Python/ceval.c:3930
#10 0x00007f6a36993a22 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x55f49f6fcfb0, nargs=3, kwnames=<optimized out>)
    at Objects/call.c:433
#11 0x00007f6a36a071c2 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#12 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3093
#13 0x00007f6a3699397a in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>) at Objects/call.c:283
#14 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x55f49f7a9530, nargs=2, kwnames=<optimized out>) at Objects/call.c:408
#15 0x00007f6a36a037a2 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#16 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#17 0x00007f6a3699397a in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at Objects/call.c:283
#18 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7f6a35eb8cb8, nargs=1, kwnames=<optimized out>) at Objects/call.c:408
#19 0x00007f6a36a037a2 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#20 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#21 0x00007f6a3699397a in function_code_fastcall (globals=<optimized out>, nargs=0, args=<optimized out>, co=<optimized out>) at Objects/call.c:283
#22 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x55f49f381240, nargs=0, kwnames=<optimized out>) at Objects/call.c:408
#23 0x00007f6a36a039c1 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#24 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3124
#25 0x00007f6a36a02631 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>,
    argcount=<optimized out>, kwnames=0x0, kwargs=0x0, kwcount=<optimized out>, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0,
    qualname=0x0) at Python/ceval.c:3930
#26 0x00007f6a36a02339 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>,
    argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3959
#27 0x00007f6a36a022fb in PyEval_EvalCode (co=co@entry=0x7f6a3618b300, globals=globals@entry=0x7f6a36298c80, locals=locals@entry=0x7f6a36298c80)
    at Python/ceval.c:524
#28 0x00007f6a36a87dfe in run_mod (mod=mod@entry=0x55f49f39eea0, filename=filename@entry=0x7f6a36190670, globals=globals@entry=0x7f6a36298c80,
--Type <RET> for more, q to quit, c to continue without paging--
    locals=locals@entry=0x7f6a36298c80, flags=flags@entry=0x7ffd5e02af8c, arena=arena@entry=0x7f6a362af390) at Python/pythonrun.c:1035
#29 0x00007f6a36a871b7 in PyRun_FileExFlags (fp=0x55f49f389260, filename_str=<optimized out>, start=<optimized out>, globals=0x7f6a36298c80,
    locals=0x7f6a36298c80, closeit=1, flags=0x7ffd5e02af8c) at Python/pythonrun.c:988
#30 0x00007f6a36a86fde in PyRun_SimpleFileExFlags (fp=0x55f49f389260, filename=<optimized out>, closeit=1, flags=0x7ffd5e02af8c)
    at Python/pythonrun.c:429
#31 0x00007f6a36a8c578 in pymain_run_file (p_cf=0x7ffd5e02af8c, filename=0x55f49f3310d0 L"GenericConsumerCLI.py", fp=0x55f49f389260)
    at Modules/main.c:427
#32 pymain_run_filename (cf=0x7ffd5e02af8c, pymain=0x7ffd5e02b060) at Modules/main.c:1606
#33 pymain_run_python (pymain=0x7ffd5e02b060) at Modules/main.c:2867
#34 pymain_main (pymain=0x7ffd5e02b060) at Modules/main.c:3028
#35 0x00007f6a36a8c26e in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:3063
#36 0x00007f6a364f509b in __libc_start_main (main=0x55f49e150050 <main>, argc=4, argv=0x7ffd5e02b1a8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffd5e02b198) at ../csu/libc-start.c:308
#37 0x000055f49e15008a in _start ()
(gdb) fr 0
#0  insertdict (value=0x0, hash=1972385545398163373, key=0x7f6a317a3c30, mp=0x7f6a317a7eb0) at Objects/dictobject.c:1009
1009    in Objects/dictobject.c
(gdb) l
1004    in Objects/dictobject.c

**Comment by walshb** [comment]
Hi. Was this with origin/master or an older revision?

I pushed a version with more error checking to my own repo https://github.com/walshb/pyavroc, branch bw-more-error-checking.

So you could rebuild from there and try it:

```
git remote add bw https://github.com/walshb/pyavroc
git remote update
git checkout -t bw/bw-more-error-checking
# depending on Jansson version, might need to run ./.travis/install_jansson.sh
./clone_avro_and_build.sh --static
```

... then you could try reading your file again.

**Comment by sebalterego** [comment]
Hi walshb,
I'm currently working with @kaustyap .
I tested your fix.  It seems to be working. In case of wrong utf-8 character encoded in a string, there is no seg fault anymore. 
Only an exception is raised : 
`_for element 'name': 'utf-8' codec can't decode byte 0x98 in position 31: invalid start byte_`

This exception can be caught with python try..except, => that's the expected behaviour.

will you merge bw/bw-more-error-checks  to the master branch, and will you create a new release soon ?

Great job !
Thank you very much.
